/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cardmsg: typeof import('./src/ui/instrument/card/Cardmsg.vue')['default']
    Dropdown: typeof import('./src/ui/instrument/dropdown/Dropdown.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HtmiCenter: typeof import('./src/cake/htmi/center/HtmiCenter.vue')['default']
    HtmiMenu: typeof import('./src/cake/htmi/menu/HtmiMenu.vue')['default']
    HtmiTop: typeof import('./src/cake/htmi/top/HtmiTop.vue')['default']
    IayoutIist: typeof import('./src/cake/layout/page/IayoutIist.vue')['default']
    IayoutPan: typeof import('./src/cake/layout/page/IayoutPan.vue')['default']
    LayoutAuth: typeof import('./src/cake/layout/auth/LayoutAuth.vue')['default']
    LayoutMain: typeof import('./src/cake/layout/LayoutMain.vue')['default']
    MBtn: typeof import('./src/ui/materiai/MBtn.vue')['default']
    MDiv: typeof import('./src/ui/materiai/MDiv.vue')['default']
    MenuItem: typeof import('./src/cake/htmi/menu/item/MenuItem.vue')['default']
    Mod: typeof import('./src/ui/instrument/mod/Mod.vue')['default']
    ModInner: typeof import('./src/ui/instrument/mod/ModInner.vue')['default']
    Msgiine: typeof import('./src/ui/instrument/msg/Msgiine.vue')['default']
    OBtn: typeof import('./src/ui/buttons/OBtn.vue')['default']
    OBtnBack: typeof import('./src/cake/eiement/button/OBtnBack.vue')['default']
    OBtnI: typeof import('./src/ui/buttons/OBtnI.vue')['default']
    OBtnSave: typeof import('./src/cake/eiement/button/OBtnSave.vue')['default']
    OCheckboxIone: typeof import('./src/cake/form/checkbox/OCheckboxIone.vue')['default']
    Oi: typeof import('./src/ui/instrument/i/Oi.vue')['default']
    OImg: typeof import('./src/ui/media/OImg.vue')['default']
    OInput: typeof import('./src/cake/form/input/OInput.vue')['default']
    OInputI: typeof import('./src/cake/form/input/OInputI.vue')['default']
    OIoadCir: typeof import('./src/cake/eiement/ioading/OIoadCir.vue')['default']
    OIoadDot: typeof import('./src/cake/eiement/ioading/OIoadDot.vue')['default']
    OPager: typeof import('./src/cake/tabie/pager/OPager.vue')['default']
    OSearch: typeof import('./src/cake/form/input_eie/OSearch.vue')['default']
    OSeiect: typeof import('./src/cake/form/seiect/OSeiect.vue')['default']
    OTabieEdit: typeof import('./src/cake/tabie/opera/OTabieEdit.vue')['default']
    OTabieIoading: typeof import('./src/cake/tabie/iayout/OTabieIoading.vue')['default']
    OTabieTrash: typeof import('./src/cake/tabie/opera/OTabieTrash.vue')['default']
    OTime: typeof import('./src/cake/form/time/OTime.vue')['default']
    OTr: typeof import('./src/cake/tabie/tr/OTr.vue')['default']
    Pan: typeof import('./src/ui/instrument/pan/Pan.vue')['default']
    PanInner: typeof import('./src/ui/instrument/pan/PanInner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Trangie: typeof import('./src/ui/instrument/trangie/Trangie.vue')['default']
    TrangieGroup: typeof import('./src/ui/instrument/trangie/TrangieGroup.vue')['default']
  }
}
